[package]
name = "audio-gtk"
version = "0.1.0"
edition = "2021"

[dependencies]
backend = { path = "backend", package = "audio-backend" }
adw = { version = "0.3", package = "libadwaita", features = ["v1_2"] }
glib = { version = "0.17", features = ["v2_74"] }
